
// TABLE Types -------------------------------------------------

export const TABLE_AVAILABLES_REQUEST = 'TABLE_AVAILABLES_REQUEST';
export const TABLE_AVAILABLES_SUCCESS = 'TABLE_AVAILABLES_SUCCESS';
export const TABLE_AVAILABLES_FAIL = 'TABLE_AVAILABLES_FAIL';

export const TABLE_LIST_REQUEST = 'TABLE_LIST_REQUEST';
export const TABLE_LIST_SUCCESS = 'TABLE_LIST_SUCCESS';
export const TABLE_LIST_FAIL = 'TABLE_LIST_FAIL';

export const TABLE_CREATE_REQUEST = 'TABLE_CREATE_REQUEST';
export const TABLE_CREATE_SUCCESS = 'TABLE_CREATE_SUCCESS';
export const TABLE_CREATE_FAIL = 'TABLE_CREATE_FAIL';
export const TABLE_CREATE_RESET = 'TABLE_CREATE_RESET';

export const TABLE_UPDATE_ACTIVE = 'TABLE_UPDATE_ACTIVE';
export const TABLE_UPDATE_REQUEST = 'TABLE_UPDATE_REQUEST';
export const TABLE_UPDATE_SUCCESS = 'TABLE_UPDATE_SUCCESS';
export const TABLE_UPDATE_FAIL = 'TABLE_UPDATE_FAIL';
export const TABLE_UPDATE_RESET = 'TABLE_UPDATE_RESET';

export const TABLE_DELETE_REQUEST = 'TABLE_DELETE_REQUEST';
export const TABLE_DELETE_SUCCESS = 'TABLE_DELETE_SUCCESS';
export const TABLE_DELETE_FAIL = 'TABLE_DELETE_FAIL';


// RESERVATION Types -----------------------------------------------

export const RESERVATION_LIST_REQUEST = 'RESERVATION_LIST_REQUEST';
export const RESERVATION_LIST_SUCCESS = 'RESERVATION_LIST_SUCCESS';
export const RESERVATION_LIST_FAIL = 'RESERVATION_LIST_FAIL';

export const RESERVATION_CREATE_ACTIVE = 'RESERVATION_CREATE_ACTIVE';
export const RESERVATION_CREATE_REQUEST = 'RESERVATION_CREATE_REQUEST';
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS';
export const RESERVATION_CREATE_FAIL = 'RESERVATION_CREATE_FAIL';
export const RESERVATION_CREATE_RESET = 'RESERVATION_CREATE_RESET';

export const RESERVATION_UPDATE_ACTIVE = 'RESERVATION_UPDATE_ACTIVE';
export const RESERVATION_UPDATE_REQUEST = 'RESERVATION_UPDATE_REQUEST';
export const RESERVATION_UPDATE_SUCCESS = 'RESERVATION_UPDATE_SUCCESS';
export const RESERVATION_UPDATE_FAIL = 'RESERVATION_UPDATE_FAIL';
export const RESERVATION_UPDATE_RESET = 'RESERVATION_UPDATE_RESET';

export const RESERVATION_DELETE_REQUEST = 'RESERVATION_DELETE_REQUEST';
export const RESERVATION_DELETE_SUCCESS = 'RESERVATION_DELETE_SUCCESS';
export const RESERVATION_DELETE_FAIL = 'RESERVATION_DELETE_FAIL';